---
channel: stable
addons:
  live555:
    repository: alex-savin/hassio-addon-live555
    target: live555
    image: smarthouseint/{arch}-addon-live555
  postgres:
    repository: alex-savin/hassio-addon-postgres
    target: postgres
    image: smarthouseint/{arch}-addon-postgres
  google-assistant-webserver:
    repository: alex-savin/hassio-addon-oogle-assistant-webserver
    target: google-assistant-webserver
    image: smarthouseint/{arch}-addon-google-assistant-webserver