---
channel: stable
addons:
  apcupsd2mqtt:
    repository: alex-savin/addon-apcupsd2mqtt
    target: apcupsd2mqtt
    image: smarthouseint/{arch}-addon-apcupsd2mqtt
  google-assistant-webserver:
    repository: alex-savin/addon-google-assistant-webserver
    target: google-assistant-webserver
    image: smarthouseint/{arch}-addon-google-assistant-webserver
  live555:
    repository: alex-savin/addon-live555
    target: live555
    image: smarthouseint/{arch}-addon-live555
  postgres:
    repository: alex-savin/addon-postgres
    target: postgres
    image: smarthouseint/{arch}-addon-postgres
  rtlamr:
    repository: alex-savin/addon-rtlamr
    target: rtlamr
    image: smarthouseint/{arch}-addon-rtlamr
  vernemq:
    repository: alex-savin/addon-vernemq
    target: vernemq
    image: smarthouseint/{arch}-addon-vernemq
  zwave2mqtt:
    repository: alex-savin/addon-zwave2mqtt
    target: zwave2mqtt
    image: smarthouseint/{arch}-addon-zwave2mqtt
