#!/usr/bin/with-contenv bash
# ==============================================================================
# SmartHouse Hass.io Add-ons: Postgres DB
# Runs the pgWeb
# ==============================================================================
source /usr/lib/hassio-addons/base.sh

# Run the pgWeb
hass.log.info "Starting pgWeb..."
exec /usr/local/bin/pgweb --bind=0.0.0.0 --listen=8081
