#!/usr/bin/with-contenv bash
# ==============================================================================
# SmartHouse Hass.io Add-ons: Live555 RTSP Proxy Server
# Runs the Live555 RTSP Proxy Server
# ==============================================================================
source /usr/lib/hassio-addons/base.sh

CONFIG_PATH=/data/options.json
STREAMS=$(jq --raw-output ".streams[]" $CONFIG_PATH)

# Run the Live555 RTSP Proxy Server
hass.log.info "Starting Live555 RTSP Proxy Server..."
exec live555ProxyServer ${STREAMS[*]}
