#!/usr/bin/with-contenv bash
# ==============================================================================
# SmartHouse Hass.io Add-ons: Postgres DB
# Runs the Postgres DB SQL Server
# ==============================================================================
source /usr/lib/hassio-addons/base.sh

# Run the Postgres DB SQL Server
hass.log.info "Starting Postgres DB SQL Server..."
exec /usr/bin/pgsql-start postgres
